### ISSUE TITLE
Upgrade impl.

### ISSUE THREAD

**Issue by JohnKhandygo** [l1feforce/RubicksCube#3]
У Вас получилось на удивление аккуратный код. Постарайтесь поддерживать его в таком состоянии, пока будете исправлять замечания. Javadoc тоже порадовал. Собственно замечания:
- [x] Уберите ненужные классы. 
- [x] По условию задачи необходимо было реализовать кубик произвольного размера. Насколько я понял, Вы поддерживаете только вариант 3x3x3.
- [x] По условиям задачи должен быть метод, который предоставляет состояние произвольной грани. 
- [ ] Подумайте, может ли метод `getCube` что-то "сломать" в Вашей реализации. То же самое касается метода `setCube`.
- [x] По условиям задачи должен быть метода поворота всего кубика в пространстве (представьте, что Вы просто повернули кубик другой гранью к себе). 
- [x] Для того, чтобы воспользоваться методом `generate` мне необходимо сначала создать экземпляр `Cube` и затем вызвать этот метод. Несколько странно, учитывая, что первый экземпляр больше никогда не понадобится. Суть в том, что для метода `generate` не важно состояние самого объекта `Cube`, поэтому имеет смысл сделать его статическим. 
- [x] То же самое касается метода `randomize`. Либо уж действительно рандомизируйте имеющийся кубик.
- [x] Вместо того, чтобы каждый раз писать `Arrays.asList(RIGHT, LOWER, LEFT, UPPER, BACK, FRONT)`, можно использовать метод `values()`, которые автоматически генерируется для всех `enum` классов, и возвращает массив (не список) всех элементов `enum` класса.
- [x] В коде не должно быть комментариев, отличных от javadoc. Если Вам приходится писать комментарии для того, чтобы Ваш код был понятен, то это плохой код.

**Comment by l1feforce** [comment]
> По условию задачи необходимо было реализовать кубик произвольного размера. Насколько я понял, Вы поддерживаете только вариант 3x3x3.

Это же было указано как бонус?

**Comment by JohnKhandygo** [comment]
Окей, согласен.

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочками в предыдущих комментариях актуально.
