### ISSUE TITLE
Upgrade tests

### ISSUE THREAD

**Issue by JohnKhandygo** [l1feforce/RubicksCube#4]
Ваши тесты почти ничего не проверяют, потому что все Ваши операции мутируют состояние объекта. То есть вот такой тестовый сценарий
```
Cube cube = new Cube().generate().randomize();
assertArrayEquals(
  cube.turnLeft(Position.BACK,1).getCube().get(Position.BACK), 
  cube.getCube().get(Position.BACK));
```
сейчас проходит просто потому, что операция `turnLeft` изменила состояние объекта `cube`. 

Касательно стиля написания тестов: в таких простых программах следует использовать концепцию [given - when - then](https://martinfowler.com/bliki/GivenWhenThen.html). Каждый тестовый метод (сценарий) должен реализовать одно given-when-then предложение. То есть не стоит, как Вы запихивать все в один метод. 

В идеале каждый тестовый сценарий должен выглядеть примерно следующим образом: 
1. (**given**) Создание куба с какой-то фиксированой (не рандомной, можете ее просто на бумажке или на настоящем кубике придумать) конфигурацией . Для того, чтобы не повторять эту операцию используйте junit аннотацию [`@Before`](http://junit.sourceforge.net/javadoc/org/junit/Before.html).
2. (**when**) Выбор какой-то грани для поворота и выполнение операции поворота.
3. (**then**) Поскольку Вы **знаете** конфигурацию кубика до поворота, Вы можете вычислить (так же, на бумаге) какой должен быть результат поворота. Создать новый кубик, конфигурация которого соответствует правильному состоянию после поворота.
4. Сравнить два кубика, тот который получился после поворота и тот, который с заведомо правильной конфигурацией. 

Примерно то же самое необходимо проделать и для других значимых методов в `Cube`.

**Comment by l1feforce** [comment]
>  Ваши тесты почти ничего не проверяют, потому что все Ваши операции мутируют состояние объекта. То есть вот такой тестовый сценарий
> 
> Cube cube = new Cube().generate().randomize();
> assertArrayEquals(
>   cube.turnLeft(Position.BACK,1).getCube().get(Position.BACK), 
>   cube.getCube().get(Position.BACK));
> 
> сейчас проходит просто потому, что операция turnLeft изменила состояние объекта cube.

Да, действительно, тесты работают когда не должны. Но я не совсем понял почему и как это исправить.

**Comment by JohnKhandygo** [comment]
Не просто 
> тесты работают когда не должны
но тесты, которые работают ничего не доказывают. В этом основная проблема. 

Текущая реализация `Cube` [мутабельная](https://www.mkyong.com/java/java-mutable-and-immutable-objects/). То есть, выполняя любые операции над экземпляром `Cube` изменяется его состояние. Например, `cube.turnLeft(Position.BACK, 1)` изменяет содержимое `Map`'а внутри класса `cube`. Именно это вызывает такой "странный" эффект с тестами.

**Comment by l1feforce** [comment]
А можете пожалуйста проверить мой коммит)

**Comment by JohnKhandygo** [comment]
- [x] Тестовый сценарий `generate` ничего не проверяет. Да и не нужен он. 
- [x] Хотелось бы увидеть еще тесты на поворот всего кубика (при `depth = 3`). И желательно с разными гранями. Для разнообразия.

**Comment by l1feforce** [comment]
А можно пожалуйста следующее задание?

**Comment by JohnKhandygo** [comment]
Написал в отдельном issue.
