### ISSUE TITLE
Task 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [l1feforce/RubicksCube#5]
**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**split**
Разбивает большой текстовый файл на маленькие файлы фиксированного размера. 

file задаёт имя входного файла.
Флаг -o ofile  задаёт базовое имя выходного файла. Если параметр отсутствует,  базовое имя выходного файла равняется “x”. Если параметр равен “-”, в качестве базового имени выходного файла следует использовать имя входного файла.
Флаг -d означает, что выходные файлы следует называть “ofile1, ofile2, ofile3, ofile4 …”, где ofile это базовое имя выходного файла. Если же этот параметр не указан, то файлы должны называться “ofileaa, ofileab, ofileac, ofilead … ofileaz ofileba ofilebb …  ”.
Флаг -l num указывает размер выходных файлов в строчках. По умолчанию выходные файлы имеют размер в 100 строчек.
Флаг -с num указывает размер выходных файлах в символах.
Флаг -n num указывает количество выходных файлов. Размер файлов при этом должен считаться автоматически.

Command line: split [-d] [-l num|-c num|-n num] [-o ofile] file

В случае, когда какое-нибудь из имён файлов указано неверно или одновременно указано несколько флагов управления размером, следует выдать ошибку. 

Кроме самой программы, следует написать автоматические тесты к ней.

Также необходимо разработать скрипты и/или инструкции сборки и запуска разработанного приложения из командной строки. 

**P.S.** Проверка второго задания начинается не раньше исправления всех замечания к первому заданию. В любом случае напишите в комментариях к этому issue, когда задание будет готово к проверке.

**P.S.S.** Если будете делать это задание в другом репозитории, дайте ссылку в комментариях к этому issue.

Рекомендуется следующий подход к разработке:
1. Реализовать класс со всей необходимой логикой так, как Вы это делали в предыдущем задании (с покрытием тестами и прочим). Другими словами, забудьте на время, что Ваше приложение должно работать из консоли.
2. Отдельно написать "обертку", которая будет парсить аргументы командной строки (используя библотеку) и вызывать разработанные на первом этапе методы. Скорее всего то, что будет написано на данном этапе даже не потребуется покрывать тестами, поскольку функциональность сторонних библотек обычно не тестируется (либо тестируется в каких-то очень сложных случаях). 

Собственно после готовности первого этапа можно начинать проверку.

**Comment by l1feforce** [comment]
> Флаг -n num указывает количество выходных файлов. Размер файлов при этом должен считаться автоматически.

А по какому принципу рассчитывать размер файлов? Ведь по факту по данной формулировке можно в любой файл любое кол-во символов вставить?

**Comment by l1feforce** [comment]
В целом уже есть что проверять, инструкцию и оставшуюся часть функционала скорее всего завтра реализую.

**Comment by JohnKhandygo** [comment]
Я просмотрел код, выглядит все весьма неплохо. Осмысленные замечания будут завтра. По поводу флага `-n`: подойдет любой более менее осмысленный вариант (раз в задании не специфицировано), только опишите в javadoc как Вы решили реализовать эту функциональность.

**Comment by JohnKhandygo** [comment]
Перенес описание задания в соответствующий репозиторий. Все замечания будут появляться там.
